# $FreeBSD: release/10.4.0/usr.bin/svn/lib/Makefile 299742 2016-05-14 10:18:27Z dim $

SUBDIR=	libapr libapr_util libserf libsqlite3 \
	libsvn_client libsvn_delta libsvn_diff libsvn_fs libsvn_fs_fs \
	libsvn_fs_util libsvn_fs_x libsvn_ra libsvn_ra_local libsvn_ra_serf \
	libsvn_ra_svn libsvn_repos libsvn_subr libsvn_wc
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
