#	$FreeBSD: release/10.4.0/libexec/tftp-proxy/Makefile 321267 2017-07-20 00:52:11Z ngie $

.PATH:	${SRCTOP}/contrib/pf/tftp-proxy

PROG=	tftp-proxy
SRCS=	tftp-proxy.c filter.c
MAN=	tftp-proxy.8

WARNS?=	3

.include <bsd.prog.mk>
