# $FreeBSD: release/10.4.0/sys/modules/ata/atapci/chipsets/Makefile 287016 2015-08-22 07:32:47Z mav $

SUBDIR += ataacard ataacerlabs ataamd ataati atacenatek atacypress atacyrix atahighpoint ataintel ataite atajmicron atamarvell atamicron atanational atanetcell atanvidia atapromise ataserverworks atasiliconimage atasis atavia

.include <bsd.subdir.mk>
