#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: release/10.4.0/usr.sbin/lpr/lptest/Makefile 321275 2017-07-20 01:07:02Z ngie $

PROG=	lptest

CFLAGS+= -I${.CURDIR:H}/common_source

.include <bsd.prog.mk>
