# $FreeBSD: release/10.4.0/lib/atf/tests/Makefile 313488 2017-02-09 22:49:48Z ngie $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/lib/atf

.PATH:		${SRCTOP}/tests
KYUAFILE=	yes

SUBDIR=		test-programs

.include <bsd.test.mk>
