#!/bin/sh
#
# $FreeBSD: release/10.4.0/etc/rc.d/FILESYSTEMS 301612 2016-06-08 13:32:00Z ngie $
#

# PROVIDE: FILESYSTEMS
# REQUIRE: root mountcritlocal cleanvar

#	This is a dummy dependency, for services which require file systems
#	to be mounted before starting.  It also serves as the default early /
#	late divider; after this point, rc.d directories are rescanned to
#	catch scripts from other file systems than /.
