#!/bin/sh
#
# $FreeBSD: release/10.4.0/etc/rc.d/msgs 306924 2016-10-09 21:28:56Z jilles $
#

# PROVIDE: msgs
# REQUIRE: LOGIN

. /etc/rc.subr

name="msgs"
start_cmd="msgs_start"
stop_cmd=":"

msgs_start()
{
	# Make a bounds file for msgs(1) if there isn't one already
	#
	if [ -d /var/msgs -a ! -f /var/msgs/bounds -a ! -L /var/msgs/bounds ]; then
		echo 0 > /var/msgs/bounds
	fi
}

load_rc_config $name
run_rc_command "$1"
