#!/bin/sh
#
# $FreeBSD: release/10.4.0/etc/rc.d/NETWORKING 301613 2016-06-08 13:34:52Z ngie $
#

# PROVIDE: NETWORKING NETWORK
# REQUIRE: netif netwait netoptions routing ppp ipfw stf faith
# REQUIRE: defaultroute mrouted route6d mroute6d resolv bridge
# REQUIRE: static_arp static_ndp

#	This is a dummy dependency, for services which require networking
#	to be operational before starting.
