# $FreeBSD: release/10.4.0/usr.sbin/bsdconfig/password/include/Makefile 279611 2015-03-05 00:34:33Z dteske $

NO_OBJ=

FILESDIR=	${LIBEXECDIR}/bsdconfig/040.password/include
FILES=		messages.subr

.include <bsd.prog.mk>
