# $FreeBSD: release/10.4.0/release/doc/en_US.ISO8859-1/Makefile 323716 2017-09-18 19:56:05Z gjb $

RELN_ROOT?= ${.CURDIR}/..

SUBDIR = relnotes
SUBDIR+= errata
SUBDIR+= hardware
SUBDIR+= installation
SUBDIR+= readme

COMPAT_SYMLINK = en

LANGCODE=en_US.ISO8859-1
_LANGCODE=en_US.ISO8859-1

.include "${RELN_ROOT}/share/mk/doc.relnotes.mk"
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
