# $FreeBSD: release/10.4.0/sys/modules/geom/geom_flashmap/Makefile 314097 2017-02-22 10:21:39Z marius $

.PATH: ${.CURDIR}/../../../geom

KMOD=	geom_flashmap
SRCS=	geom_flashmap.c

.include <bsd.kmod.mk>
