# $FreeBSD: release/10.4.0/usr.sbin/bsdconfig/examples/Makefile 279611 2015-03-05 00:34:33Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/examples/bsdconfig
FILES=		add_some_packages.sh browse_packages_http.sh bsdconfigrc

.include <bsd.prog.mk>
