# $FreeBSD: release/10.4.0/usr.bin/svn/Makefile 299742 2016-05-14 10:18:27Z dim $

SUBDIR=	lib .WAIT \
	svn svnadmin svnbench svndumpfilter svnfsfs svnlook svnserve \
	svnsync svnversion svnmucc svnrdump
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
