# $FreeBSD: release/10.4.0/usr.sbin/bsdconfig/password/share/Makefile 279611 2015-03-05 00:34:33Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/bsdconfig/password
FILES=		password.subr

.include <bsd.prog.mk>
