# $FreeBSD: release/10.4.0/usr.sbin/cpucontrol/Makefile 308761 2016-11-17 15:17:01Z avg $

PROG=	cpucontrol
MAN=	cpucontrol.8
SRCS=	cpucontrol.c intel.c amd.c amd10h.c via.c

NO_WCAST_ALIGN=

.include <bsd.prog.mk>
